name: Publish

on:
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: |
        npm run format-check
        npm run lint
    - name: Build
      run: npm run build
    - name: Publish
      if: success()
      uses: crazy-max/ghaction-github-pages@f9f3f30a16cddca57ef4e3df0b01ed823c1c1355
      with:
        target_branch: master
        build_dir: dist
        commit_name: PixelGrid CI
        commit_email: pixelgrid@zwezdin.com
        commit_message: Automated deploy
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
